import { getSupabase, isSupabaseConfigured } from '../lib/supabase';
import { 
  Product, 
  Category, 
  Worker, 
  Shift, 
  Sale, 
  SaleItem, 
  Customer, 
  NotificationItem, 
  ActivityLog, 
  BusinessSettings, 
  AdminUser,
  PaymentMethod 
} from '../types';

// Default initial settings
export const DEFAULT_SETTINGS: BusinessSettings = {
  business_name: 'MUNAJ BAR',
  phone: '+234 803 123 4567',
  email: 'admin@munajbar.com',
  address: 'Plot 18, Commercial Avenue, Victoria Island, Lagos, Nigeria',
  logo_url: '',
  receipt_header: 'MUNAJ BAR & LOUNGE\nCold Drinks, Great Vibes & Premium Service',
  receipt_footer: 'Thank you for choosing MUNAJ BAR.\nPlease come again!',
  vat_percentage: 7.5,
  show_cashier: true,
  show_receipt_number: true,
  currency_symbol: '₦',
  currency_code: 'NGN',
};

// Initial Seed Data for immediate testing & fallback if database is brand new
export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Beer & Ciders', description: 'Chilled local and imported beers', status: 'active', sort_order: 1 },
  { id: 'cat-2', name: 'Whiskey & Spirits', description: 'Premium blended & single malt whiskeys', status: 'active', sort_order: 2 },
  { id: 'cat-3', name: 'Cocktails & Mixes', description: 'Signature and classic mixed drinks', status: 'active', sort_order: 3 },
  { id: 'cat-4', name: 'Wine & Champagne', description: 'Red, white, sparkling and vintage wines', status: 'active', sort_order: 4 },
  { id: 'cat-5', name: 'Non-Alcoholic & Energy', description: 'Soft drinks, juices and energy boosters', status: 'active', sort_order: 5 },
  { id: 'cat-6', name: 'Bar Bites & Grills', description: 'Suya, peppered wings and finger foods', status: 'active', sort_order: 6 },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Heineken Lager (600ml)',
    sku: 'BEER-HEIN-600',
    category_id: 'cat-1',
    category_name: 'Beer & Ciders',
    selling_price: 1500,
    cost_price: 900,
    stock_quantity: 48,
    min_stock_level: 10,
    description: 'Chilled premium Heineken bottle',
    status: 'active',
  },
  {
    id: 'prod-2',
    name: 'Guinness Foreign Extra Stout',
    sku: 'BEER-GUIN-600',
    category_id: 'cat-1',
    category_name: 'Beer & Ciders',
    selling_price: 1600,
    cost_price: 1000,
    stock_quantity: 36,
    min_stock_level: 12,
    description: 'Rich dark stout',
    status: 'active',
  },
  {
    id: 'prod-3',
    name: 'Budweiser Bottle',
    sku: 'BEER-BUD-600',
    category_id: 'cat-1',
    category_name: 'Beer & Ciders',
    selling_price: 1400,
    cost_price: 850,
    stock_quantity: 4,
    min_stock_level: 10,
    description: 'King of beers',
    status: 'active',
  },
  {
    id: 'prod-4',
    name: 'Hennessy VS (700ml)',
    sku: 'SPIR-HENN-VS',
    category_id: 'cat-2',
    category_name: 'Whiskey & Spirits',
    selling_price: 55000,
    cost_price: 42000,
    stock_quantity: 12,
    min_stock_level: 3,
    description: 'Very Special Cognac',
    status: 'active',
  },
  {
    id: 'prod-5',
    name: 'Johnnie Walker Black Label',
    sku: 'WHIS-JW-BLK',
    category_id: 'cat-2',
    category_name: 'Whiskey & Spirits',
    selling_price: 32000,
    cost_price: 24000,
    stock_quantity: 8,
    min_stock_level: 2,
    description: '12 Year Old Blended Scotch',
    status: 'active',
  },
  {
    id: 'prod-6',
    name: 'Jameson Irish Whiskey',
    sku: 'WHIS-JMSN-STD',
    category_id: 'cat-2',
    category_name: 'Whiskey & Spirits',
    selling_price: 26000,
    cost_price: 19500,
    stock_quantity: 0,
    min_stock_level: 4,
    description: 'Smooth triple distilled Irish whiskey',
    status: 'out_of_stock',
  },
  {
    id: 'prod-7',
    name: 'Munaj Signature Mojito',
    sku: 'CKTL-MNJ-MOJ',
    category_id: 'cat-3',
    category_name: 'Cocktails & Mixes',
    selling_price: 4500,
    cost_price: 1800,
    stock_quantity: 50,
    min_stock_level: 10,
    description: 'Fresh mint, lime, rum and club soda',
    status: 'active',
  },
  {
    id: 'prod-8',
    name: 'Long Island Iced Tea',
    sku: 'CKTL-LNG-ISL',
    category_id: 'cat-3',
    category_name: 'Cocktails & Mixes',
    selling_price: 5500,
    cost_price: 2200,
    stock_quantity: 35,
    min_stock_level: 5,
    description: 'Vodka, rum, gin, tequila, triple sec & cola',
    status: 'active',
  },
  {
    id: 'prod-9',
    name: 'Moët & Chandon Brut Impérial',
    sku: 'WINE-MOET-IMP',
    category_id: 'cat-4',
    category_name: 'Wine & Champagne',
    selling_price: 95000,
    cost_price: 75000,
    stock_quantity: 6,
    min_stock_level: 2,
    description: 'Iconic French Champagne',
    status: 'active',
  },
  {
    id: 'prod-10',
    name: 'Red Bull Energy Drink (250ml)',
    sku: 'NVOL-RED-BULL',
    category_id: 'cat-5',
    category_name: 'Non-Alcoholic & Energy',
    selling_price: 2000,
    cost_price: 1200,
    stock_quantity: 60,
    min_stock_level: 15,
    description: 'Vitalizes body and mind',
    status: 'active',
  },
  {
    id: 'prod-11',
    name: 'Peppered Goat Meat (Asun)',
    sku: 'FOOD-ASUN-MED',
    category_id: 'cat-6',
    category_name: 'Bar Bites & Grills',
    selling_price: 6000,
    cost_price: 3200,
    stock_quantity: 25,
    min_stock_level: 5,
    description: 'Spicy roasted goat meat with habanero peppers',
    status: 'active',
  },
];

export const SEED_WORKERS: Worker[] = [
  {
    id: 'wrk-1',
    name: 'John Adebayo',
    email: 'john.pos@munajbar.com',
    role: 'cashier',
    phone: '+234 802 111 2233',
    status: 'on_shift',
    current_shift_id: 'shift-101',
    shift_start: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    last_activity: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    total_sales_today: 147500,
    transactions_count_today: 8,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'wrk-2',
    name: 'Jane Nwosu',
    email: 'jane.bar@munajbar.com',
    role: 'bartender',
    phone: '+234 803 444 5566',
    status: 'on_shift',
    current_shift_id: 'shift-102',
    shift_start: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    last_activity: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    total_sales_today: 86000,
    transactions_count_today: 5,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'wrk-3',
    name: 'Emmanuel Okafor',
    email: 'emmanuel.pos@munajbar.com',
    role: 'cashier',
    phone: '+234 807 777 8899',
    status: 'offline',
    current_shift_id: null,
    shift_start: null,
    last_activity: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    total_sales_today: 0,
    transactions_count_today: 0,
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
];

export const SEED_SHIFTS: Shift[] = [
  {
    id: 'shift-101',
    worker_id: 'wrk-1',
    worker_name: 'John Adebayo',
    start_time: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    end_time: null,
    opening_cash: 20000,
    expected_cash: 58000,
    actual_cash: null,
    cash_difference: null,
    cash_sales: 38000,
    pos_sales: 74500,
    transfer_sales: 35000,
    total_sales: 147500,
    transactions_count: 8,
    items_sold_count: 24,
    status: 'open',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'shift-102',
    worker_id: 'wrk-2',
    worker_name: 'Jane Nwosu',
    start_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    end_time: null,
    opening_cash: 15000,
    expected_cash: 41000,
    actual_cash: null,
    cash_difference: null,
    cash_sales: 26000,
    pos_sales: 60000,
    transfer_sales: 0,
    total_sales: 86000,
    transactions_count: 5,
    items_sold_count: 14,
    status: 'open',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Chief Tunde Balogun',
    phone: '+234 803 555 1212',
    email: 'tunde.b@gmail.com',
    total_purchases: 18,
    total_spending: 485000,
    last_purchase_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    orders_count: 18,
    notes: 'VIP guest, prefers Hennessy VS and table 4',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'cust-2',
    name: 'Dr. Stella Briggs',
    phone: '+234 809 333 4411',
    email: 'stella.briggs@yahoo.com',
    total_purchases: 9,
    total_spending: 172000,
    last_purchase_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    orders_count: 9,
    notes: 'Wine lover, Moet Champagne regular',
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'cust-3',
    name: 'Michael Danjuma',
    phone: '+234 814 888 9900',
    email: 'm.danjuma@outlook.com',
    total_purchases: 5,
    total_spending: 54000,
    last_purchase_at: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    orders_count: 5,
    notes: 'Friday night regular, Heineken enthusiast',
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const SEED_SALES: Sale[] = [
  {
    id: 'sale-1001',
    receipt_number: 'MB-10245',
    date: new Date().toISOString().split('T')[0],
    time: '14:22',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    worker_id: 'wrk-1',
    worker_name: 'John Adebayo',
    shift_id: 'shift-101',
    customer_id: 'cust-1',
    customer_name: 'Chief Tunde Balogun',
    subtotal: 55000,
    discount: 0,
    vat: 4125,
    grand_total: 59125,
    payment_method: 'POS',
    status: 'completed',
    printed_by: 'John Adebayo (POS)',
    printed_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    notes: 'VIP Lounge Table 2',
    items: [
      {
        id: 'item-1',
        sale_id: 'sale-1001',
        product_id: 'prod-4',
        product_name: 'Hennessy VS (700ml)',
        sku: 'SPIR-HENN-VS',
        quantity: 1,
        unit_price: 55000,
        cost_price: 42000,
        total_price: 55000,
      }
    ]
  },
  {
    id: 'sale-1002',
    receipt_number: 'MB-10246',
    date: new Date().toISOString().split('T')[0],
    time: '14:55',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    worker_id: 'wrk-2',
    worker_name: 'Jane Nwosu',
    shift_id: 'shift-102',
    customer_id: null,
    customer_name: 'Walk-in Guest',
    subtotal: 21000,
    discount: 0,
    vat: 1575,
    grand_total: 22575,
    payment_method: 'Cash',
    status: 'completed',
    printed_by: 'Jane Nwosu (POS)',
    printed_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    notes: 'Counter Order',
    items: [
      {
        id: 'item-2',
        sale_id: 'sale-1002',
        product_id: 'prod-1',
        product_name: 'Heineken Lager (600ml)',
        sku: 'BEER-HEIN-600',
        quantity: 6,
        unit_price: 1500,
        cost_price: 900,
        total_price: 9000,
      },
      {
        id: 'item-3',
        sale_id: 'sale-1002',
        product_id: 'prod-11',
        product_name: 'Peppered Goat Meat (Asun)',
        sku: 'FOOD-ASUN-MED',
        quantity: 2,
        unit_price: 6000,
        cost_price: 3200,
        total_price: 12000,
      }
    ]
  },
  {
    id: 'sale-1003',
    receipt_number: 'MB-10247',
    date: new Date().toISOString().split('T')[0],
    time: '15:10',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    worker_id: 'wrk-1',
    worker_name: 'John Adebayo',
    shift_id: 'shift-101',
    customer_id: null,
    customer_name: 'Walk-in Guest',
    subtotal: 35000,
    discount: 0,
    vat: 2625,
    grand_total: 37625,
    payment_method: 'Transfer',
    status: 'completed',
    printed_by: 'John Adebayo (POS)',
    printed_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    notes: 'Confirmed via Moniepoint POS',
    items: [
      {
        id: 'item-4',
        sale_id: 'sale-1003',
        product_id: 'prod-5',
        product_name: 'Johnnie Walker Black Label',
        sku: 'WHIS-JW-BLK',
        quantity: 1,
        unit_price: 32000,
        cost_price: 24000,
        total_price: 32000,
      },
      {
        id: 'item-5',
        sale_id: 'sale-1003',
        product_id: 'prod-1',
        product_name: 'Heineken Lager (600ml)',
        sku: 'BEER-HEIN-600',
        quantity: 2,
        unit_price: 1500,
        cost_price: 900,
        total_price: 3000,
      }
    ]
  }
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'NEW SALE',
    message: 'John Adebayo completed sale #MB-10245 of ₦59,125.',
    type: 'new_sale',
    date: new Date().toISOString().split('T')[0],
    time: '14:22',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    is_read: false,
    metadata: { sale_id: 'sale-1001', amount: 59125 },
  },
  {
    id: 'notif-2',
    title: 'LOW STOCK ALERT',
    message: 'Budweiser Bottle is running low. Only 4 units remaining (Min: 10).',
    type: 'low_stock',
    date: new Date().toISOString().split('T')[0],
    time: '13:45',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    is_read: false,
    metadata: { product_id: 'prod-3', current_stock: 4 },
  },
  {
    id: 'notif-3',
    title: 'OUT OF STOCK ALERT',
    message: 'Jameson Irish Whiskey is now OUT OF STOCK.',
    type: 'out_of_stock',
    date: new Date().toISOString().split('T')[0],
    time: '12:30',
    timestamp: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    is_read: true,
    metadata: { product_id: 'prod-6' },
  },
  {
    id: 'notif-4',
    title: 'WORKER STARTED SHIFT',
    message: 'Jane Nwosu started a new shift with ₦15,000 opening cash.',
    type: 'worker_shift_start',
    date: new Date().toISOString().split('T')[0],
    time: '12:00',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    is_read: true,
    metadata: { worker_id: 'wrk-2', shift_id: 'shift-102' },
  },
  {
    id: 'notif-5',
    title: 'WORKER STARTED SHIFT',
    message: 'John Adebayo started a new shift with ₦20,000 opening cash.',
    type: 'worker_shift_start',
    date: new Date().toISOString().split('T')[0],
    time: '10:00',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    is_read: true,
    metadata: { worker_id: 'wrk-1', shift_id: 'shift-101' },
  },
];

export const SEED_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-1',
    user_name: 'John Adebayo',
    user_role: 'cashier',
    action: 'Sale Completed',
    description: 'Completed sale #MB-10245 for ₦59,125 via POS',
    entity_type: 'sale',
    entity_id: 'sale-1001',
    timestamp: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '14:22',
  },
  {
    id: 'act-2',
    user_name: 'Jane Nwosu',
    user_role: 'bartender',
    action: 'Sale Completed',
    description: 'Completed sale #MB-10246 for ₦22,575 via Cash',
    entity_type: 'sale',
    entity_id: 'sale-1002',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '14:55',
  },
  {
    id: 'act-3',
    user_name: 'John Adebayo',
    user_role: 'cashier',
    action: 'Sale Completed',
    description: 'Completed sale #MB-10247 for ₦37,625 via Bank Transfer',
    entity_type: 'sale',
    entity_id: 'sale-1003',
    timestamp: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '15:10',
  },
  {
    id: 'act-4',
    user_name: 'Super Admin',
    user_role: 'super_admin',
    action: 'Admin Login',
    description: 'Admin signed in to MUNAJ BAR Administration Console',
    entity_type: 'settings',
    timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '13:40',
  },
  {
    id: 'act-5',
    user_name: 'Jane Nwosu',
    user_role: 'bartender',
    action: 'Shift Started',
    description: 'Opened shift #shift-102 with ₦15,000 opening float',
    entity_type: 'shift',
    entity_id: 'shift-102',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '12:00',
  },
  {
    id: 'act-6',
    user_name: 'John Adebayo',
    user_role: 'cashier',
    action: 'Shift Started',
    description: 'Opened shift #shift-101 with ₦20,000 opening float',
    entity_type: 'shift',
    entity_id: 'shift-101',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    date: new Date().toISOString().split('T')[0],
    time: '10:00',
  },
];
